name: test
on:
  - push
  - pull_request

permissions:
  contents: read

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          check-latest: true
          cache: false
      - name: Download Go modules
        run: go mod download
      - name: Lint
        uses: golangci/golangci-lint-action@v8
      - name: Build
        run: ./.github/build.sh
      - name: Test
        run: go test -v ./...
